// /api/generate-report/route.tsx
import { NextRequest, NextResponse } from 'next/server';
import { openai } from '@/config/OpenAiModel'; 
import  db  from '@/config/db'; 
import { sessionChatsTable } from '@/config/schema'; 
import { eq } from 'drizzle-orm'; 

export async function POST(req: NextRequest) {
  const { messages, sessionDetail, sessionid } = await req.json();

  if (!messages || !Array.isArray(messages) || messages.length === 0) {
    return NextResponse.json({ error: 'Messages are required' }, { status: 400 });
  }

  try {
    // Prepare the conversation transcript for OpenAI
    const conversationText = messages
      .map((msg: { role: string; transcript: string }) => `${msg.role}: ${msg.transcript}`)
      .join('\n');

    // Craft a detailed prompt for report generation
    const systemPrompt = `
      You are an AI Medical Voice Agent that just finished a voice conversation with a user. Based on the Doctor AI agent info and the converstaion of the doctor with the user, generate a structured report with the following fields:

sessionId: a unique session identifier

agent: the medical specialist name (e.g., "General Physician AI")

user: name of the patient or "Anonymous" if not provided

timestamp: current date and time in ISO format

chiefComplaint: one-sentence summary of the main health concern

summary: a 2-3 sentence summary of the conversation, symptoms, and recommendations

symptoms: list of symptoms mentioned by the user

duration: how long the user has experienced the symptoms

severity: mild, moderate, or severe

medicationsMentioned: list of any medicines mentioned

recommendations: list of AI suggestions (e.g., rest, see a doctor)

Return the result in this JSON format:

{
  "sessionId": "string",
  "agent": "string",
  "user": "string",
  "timestamp": "ISO Date string",
  "chiefComplaint": "string",
  "summary": "string",
  "symptoms": ["symptom1", "symptom2"],
  "duration": "string",
  "severity": "string",
  "medicationsMentioned": ["med1", "med2"],
  "recommendations": ["rec1", "rec2"]
}


Only include valid fields. Respond with nothing else.
    `;

    const userPrompt = `Conversation Transcript:\n${conversationText}\n\nGenerate the report now.`;

    // Call OpenAI to generate the report
    const completion = await openai.chat.completions.create({
      model: 'openai/gpt-3.5-turbo', // Or your preferred model
      messages: [
        { role: 'system', content: systemPrompt },
        { role: 'user', content: userPrompt }
      ],
      max_tokens: 1000,
      temperature: 0.3 // Low temperature for factual reports
    });

    const report = completion.choices[0]?.message?.content?.trim();
    if (!report) {
      throw new Error('No report generated by OpenAI');
    }


    const result = await db.update(sessionChatsTable).set({ report: report ,conversation: messages }).where(eq(sessionChatsTable.sessionId, sessionid));

    return NextResponse.json({
      success: true,
      report,
      sessionId: sessionid
    });

  } catch (error) {
    console.error('Error generating report:', error);
    return NextResponse.json({
      error: 'Failed to generate report',
      details: error instanceof Error ? error.message : 'Unknown error'
    }, { status: 500 });
  }
}